### ISSUE TITLE
Initial API call is slow

### ISSUE THREAD

**Issue by JimBobSquarePants** [JimBobSquarePants/GithubReleaseNotesGenerator#1]
I haven't figured out a way yet to filter the initial call to retrieve PRs from the repository by commit/date. This single call takes about 90% of the total time to retrieve the release notes which is a poor experience.

https://github.com/JimBobSquarePants/GithubReleaseNotesGenerator/blob/3b8c1d7176de7848964a46fe2939f2bb9b5d6197/src/GithubReleaseNotesGenerator/Infrastructure/ReleaseNotes.cs#L127-L134

**Comment by eduherminio** [comment]
Hi @JimBobSquarePants!
It might be worth giving a try to `Client.Search.SearchIssues`:
```csharp
            var prRequest = new SearchIssuesRequest()
            {
                Type = IssueTypeQualifier.PullRequest,
                Updated = new DateRange(fromOffset, toOffset),
                State = ItemState.Closed,
                Repos = new RepositoryCollection { $"{owner}/{repository}" }
            };

            var issues = await this.GitHubClient.Search.SearchIssues(prRequest);
```

I'm getting very similar results (a superset, in fact) in a fraction of time:

![image](https://user-images.githubusercontent.com/11148519/88224193-eb9fb980-cc68-11ea-8dff-4de16061cd52.png)

You'd need to refactor the rest of the code, but it seems to be worth it even in the worst case scenario where you have to get those PRs individually using `GitHubClient.PullRequests` (due to not having all the info needed).

**Comment by JimBobSquarePants** [comment]
@eduherminio Thanks for this, much appreciated, that's definitely much faster!

That superset you saw btw was because you were filtering by "update" date not "closed". It was picking up comments added to old PRs.
